name: Unit Tests

on:
  pull_request:
    types: [opened, edited, labeled, unlabeled, synchronize]

jobs:
  test_x86_64:
    name: "Build 3.8 on ubuntu-latest"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --disable-pip-version-check --upgrade pip
          pip install -U -r requirements.txt -r requirements-dev.txt
          #Install locally to support tests
          pip install -e .
      - name: Test with pytest
        run: pytest
